### ISSUE TITLE
Wrong License

### ISSUE THREAD

**Issue by py-crash** [aerohub/hugo-orbit-theme#20]
This project is licenced under [CC BY](https://creativecommons.org/licenses/by/3.0/). However, the original [orbit template says](https://github.com/xriley/Orbit-Theme#author--license): 

> You do not have the rights to resell, sublicense or redistribute (even for free) the template on its own or as a separate attachment from any of your work.

That is incompatible with the CC BY licence because I won't be able to redistribute the work nor use it in any commercial project.

**Comment by Swissbite** [comment]
At the date this copy was made (last commit was created May 15, 2017), the license was CC BY. The corresponding commit is https://github.com/xriley/Orbit-Theme/blob/355f83f7a2859999ac4a22d523eae9113c4f27d6/README.md

**Comment by py-crash** [comment]
Thank you for clarifying!
