### ISSUE TITLE
.Now will be deprecated with Hugo v0.20

### ISSUE THREAD

**Issue by digitalcraftsman** [aerohub/hugo-orbit-theme#5]
`.Now` will be deprecated replaced with the `now` template function in Hugo v0.20 which eventually will be released on Monday. It's likely that the deprecation will cause builds to fail.

**Comment by jannecederberg** [comment]
This seems to have been addressed by 41f922f1a13abb3d532e1a0f4d526ea5534dd2fd but wasn't closed.

**Comment by digitalcraftsman** [comment]
It looks fine now. Thanks :+1:

**Comment by jannecederberg** [comment]
No problemo!
