### ISSUE TITLE
Hugo-me-theme can't be found

### ISSUE THREAD

**Issue by digitalcraftsman** [aerohub/hugo-orbit-theme#6]
Hello @ryugibo,

the theme list at spf13/hugoThemes references the hugo-me-theme with the URL https://github.com/aerohub/hugo-me-theme. However, this URL doesn't point to an existing repo nor does your account have a similarly named theme.

Please let me know if you've moved/deleted your theme so we can update theme list accordingly.

Cheers,
Digitalcraftsman

**Comment by aerohub** [comment]
Hello @digitalcraftsman The theme is broken and I have no time to repair it and make it good. Sorry, but I think it would be better to delete it.

**Comment by digitalcraftsman** [comment]
Thank you for the update. I'll remove the reference from the list.
